Integrate BE and FE
automatarium/automatarium pull request #116
Opened 2022-05-23 09:58 UTC by giraugh

2022-05-23 11:23 UTC, tdib commented on frontend/src/components/Label/Label.js
> +    /* content: '${props => !props.$required ? ' (optional)' : ''}'; */
imagine committing comments

2022-05-23 11:25 UTC, tdib commented on frontend/src/index.js
> +      <Route path="/svg" element={<GraphView style={{ width: '100vw', height: '100vh' }} />} />
We don't need this page anymore do we?

2022-05-23 11:25 UTC, giraugh commented on frontend/src/index.js
> +      <Route path="/svg" element={<GraphView style={{ width: '100vw', height: '100vh' }} />} />
Yeah, probably not. Will remove

2022-05-23 11:32 UTC, tdib approved these changes
It appears good to myself

2022-05-23 11:49 UTC, Prydeton requested changes
I refuse to accept until Ewan deciphers the code and tells me what it says

2022-05-23 12:19 UTC, GRA0007 requested changes
Other notes:
- From the login/signup pages, there's no way for me to go back to the homepage or the editor
- I think this is mentioned on the file but we already have a secondary button, is there a need for an outlined version? Especially because the share button should be hidden if you're logged out.

2022-05-23 12:19 UTC, GRA0007 commented on frontend/src/pages/About/About.js
> +    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Varius vestibulum pretium velit vitae euismod magna mi, in. Erat nulla risus, tellus diam. Faucibus sagittis parturient convallis egestas
Hm I like this copy but it's a little hard to read, maybe it's the latin? It might just be me...

2022-05-23 12:19 UTC, GRA0007 commented on frontend/src/pages/NewFile/components/NewProjectCard/NewProjectCard.js
> +const NewProjectCard = ({ title, description, disabled, ...props }) => {
Also this file too please :>

2022-05-23 12:19 UTC, GRA0007 commented on frontend/src/pages/Signup/Signup.js
> +      <Button type='submit' disabled={!isDirty || isSubmitting}>Signup</Button>
Can signup be two words please: Sign up

2022-05-23 12:19 UTC, GRA0007 commented on frontend/src/components/Footer/footerStyle.js
> +  position: fixed;
Sorry but I don't like how the footer is always onscreen, it should just be at the bottom of the page

2022-05-23 12:22 UTC, giraugh commented on frontend/src/components/Button/Button.js
> +  border,
oh, just coz its invisible on the toolbar colour

2022-05-23 12:23 UTC, giraugh commented on frontend/src/pages/Editor/components/Menubar/Menubar.js
> +            <Button secondary border onClick={() => confirm('You will lose any unsaved work. Continue?') && navigate('/login')}>Log In</Button>
I realised this after the fact lol

2022-05-23 12:26 UTC, GRA0007 commented on frontend/src/components/Button/Button.js
> +  border,
Ah, maybe we can do a stevent and have a `surface` prop to use the `background` colour instead 🤔 Happy to discuss this on a call

2022-05-23 12:26 UTC, GRA0007 commented on frontend/src/pages/Editor/components/Menubar/Menubar.js
> +            <Button secondary border onClick={() => confirm('You will lose any unsaved work. Continue?') && navigate('/login')}>Log In</Button>
No stress, up to you if you wanna do this now or in another PR, if the latter please make an issue for it

2022-05-24 02:28 UTC, giraugh commented on frontend/src/pages/Editor/components/Menubar/Menubar.js
> +            <Button secondary border onClick={() => confirm('You will lose any unsaved work. Continue?') && navigate('/login')}>Log In</Button>
@GRA0007 Currently thinking that the login/signup would make more sense as modals on the editor page. That way this isn't necessary and it also solves the problem of navigating to and from those pages.

2022-05-24 02:36 UTC, GRA0007 commented on frontend/src/pages/Editor/components/Menubar/Menubar.js
> +            <Button secondary border onClick={() => confirm('You will lose any unsaved work. Continue?') && navigate('/login')}>Log In</Button>
> @GRA0007 Currently thinking that the login/signup would make more sense as modals on the editor page. That way this isn't necessary and it also solves the problem of navigating to and from those pages.

I approve of this message

2022-05-24 02:37 UTC, giraugh commented on frontend/src/pages/Editor/components/Menubar/Menubar.js
> +            <Button secondary border onClick={() => confirm('You will lose any unsaved work. Continue?') && navigate('/login')}>Log In</Button>
Also, I don't think `beforeunload` will trigger because the navigation is done w/ react router.

2022-05-24 02:45 UTC, GRA0007 commented on frontend/src/pages/Editor/components/Menubar/Menubar.js
> +            <Button secondary border onClick={() => confirm('You will lose any unsaved work. Continue?') && navigate('/login')}>Log In</Button>
Oh damn it looks like they skipped out on this feature in v6
https://reactrouter.com/docs/en/v6/upgrading/v5#prompt-is-not-currently-supported

2022-05-24 02:55 UTC, GRA0007 approved these changes
'h','a','r','l','a','n','d'

2022-05-24 03:02 UTC, merged