Implement Info Pane
automatarium/automatarium pull request #149
Opened 2022-06-10 16:54 UTC by giraugh

<img width="399" alt="image" src="https://user-images.githubusercontent.com/16392483/173114521-b4aa9683-57b5-4757-99cd-da893800cb51.png">

2022-06-10 17:10 UTC, tdib approved these changes
LGTM

2022-06-11 03:01 UTC, GRA0007 requested changes
Looks good!

2022-06-11 03:01 UTC, GRA0007 commented on frontend/src/components/Sidepanel/Panels/Info/Info.js
> +  })
All of these `useMemo`s are missing deps, making them ineffective

2022-06-11 03:01 UTC, GRA0007 commented on frontend/src/components/Sidepanel/Panels/Info/infoStyle.js
> +    border-color: white;
This needs to be `var(--table-border-color)`

2022-06-11 06:02 UTC, GRA0007 approved these changes
Cheese gromit

2022-06-11 06:02 UTC, merged