Allow panning view with touchpad
automatarium/automatarium pull request #208
Opened 2022-06-16 13:50 UTC by GRA0007

Mouse users must now hold ctrl to zoom with the scroll wheel. This also fixes the position slipping while zooming occasionally, an issue that was caused due to the position and zoom being set separately while zooming.

2022-06-16 13:53 UTC, GRA0007 commented
(also I checked mathematically and the zoom indicator on the bottom of the toolbar is accurate)

2022-06-18 10:36 UTC, tdib requested changes
So it works on Windows fine (and presumably better on MacOS), but I do think the default for Windows should be to scroll by default rather than holding ctrl seeing as this isn't really a "scroll context" and as always a preference for this would be nice.

2022-06-18 10:47 UTC, GRA0007 commented
> So it works on Windows fine (and presumably better on MacOS), but I do think the default for Windows should be to scroll by default rather than holding ctrl seeing as this isn't really a "scroll context" and as always a preference for this would be nice.

Ok as discussed this should be a separate issue

2022-06-18 15:46 UTC, tdib approved these changes
LGTM

2022-06-18 15:46 UTC, merged