Fix/height differences
automatarium/automatarium pull request #344
Opened 2023-04-17 00:45 UTC by ire4ever1190

Closes #299 

![image](https://user-images.githubusercontent.com/19339842/232353723-b89f7e35-c5f2-4832-a572-9e0e2f947667.png)

Reason I'm doing the issue is because I was only able to reproduce on my laptop

The root cause seemed to be font sizes. My chrome had a smaller font size so it could fit everything but my Firefox uses my system font which is a bit bigger so took more space in the first card. This makes the cards be based relative to the size of the fonts and should allow for roughly ~5 lines of text per card.

Requested multiple reviewers so that it can be tested on different font sizes and computers to make sure the changes don't cause weirdness for anyone else

2023-04-17 02:34 UTC, SidhraFernando-Plant submitted a review, later dismissed
I am a little concerned about the added space after the text:

<img width="998" alt="Screen Shot 2023-04-17 at 12 18 51 pm" src="https://user-images.githubusercontent.com/79517325/232363409-c49a2124-0d3f-4f9f-95e5-f968089d9668.png">

A few thoughts:
- Is there any way the values can be adjusted to prevent this?
- More space at the bottom would probably be fine as long as the space at the top is the same, ie. text is vertically centred

2023-04-18 06:39 UTC, LvandoApps requested changes
Yeah formatting is off

2023-05-16 23:47 UTC, ire4ever1190 commented
In the end I just calculated the height for the tallest card and set the rest to that.

Seemed to be the easiest solution since it means no fiddling with fonts, css, etc
Also means it is future proof and wont need changing if any text is added/removed

2023-05-16 23:48 UTC, ire4ever1190 commented on frontend/src/pages/NewFile/components/NewProjectCard/newProjectCardStyle.ts
> +  height: ${p => p.height || '100%'}px;
In case there is a problem in the state, we just set the height to 100% so its least usable

2023-05-18 06:31 UTC, LvandoApps approved these changes
Good!

2023-05-18 06:32 UTC, merged